### ISSUE TITLE
Do not have access to data

### ISSUE THREAD

**Issue by LouisDo2108** [wang-zhanyu/MSAT#1]
Hi.

The Google Drive link is not public, so I could not download the data. I would like to know if there is any plan for this data to be public for download.

Thank you.

**Comment by wang-zhanyu** [comment]
Hi, we used the same dataset partition as R2Gen, the data link is referenced from https://github.com/cuhksz-nlp/R2Gen, I'm not sure why it's not accessible now. Maybe you can try requesting access to this link, or directly apply for access to the original data from https://physionet.org/content/mimic-cxr-jpg/2.0.0/.
