### ISSUE TITLE
annotation.json file

### ISSUE THREAD

**Issue by Drwr97** [wang-zhanyu/MSAT#6]
How do I get the annotation.json file for the MIMIC-CXR dataset? When I want to access the link you gave, he asked me to pass the review, can you approve my download request? That's very helpful. Thank you.

**Comment by wang-zhanyu** [comment]
Hi, the link to this data is quoted from [R2Gen](https://github.com/cuhksz-nlp/R2Gen), I'm not sure why it's not accessible now. You can download the annotation file from [here](https://drive.google.com/file/d/1QUJCo4uTF-x6vRqgDap5YXpALi72j_-V/view?usp=sharing), but you may need to apply the access permission from [the data owner](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) to download the original image data.

**Comment by Drwr97** [comment]
Thank you very much for your reply. When I ran the extract_clip_feature.py file, an error was reported in line 13. There were no images in the json file you provided, did you process the dataset? Can you provide a processed json file so that I can extract visual features? Looking forward to your reply.

**Comment by wang-zhanyu** [comment]
Hi, you can download the annotation.json file with image path from [Here](https://drive.google.com/file/d/1QUJCo4uTF-x6vRqgDap5YXpALi72j_-V/view?usp=sharing), but you need to download the original image data yourself.

**Comment by Drwr97** [comment]
I have downloaded the pictures of MIMIC data set, but when I used Clip to extract the features, I found that you seemed to use a file called mimic.json that you have processed yourself, can you provide it? Thank you very much.

**Comment by wang-zhanyu** [comment]
Just replace the 'annotation' with the path of the file you downloaded from the link I provided, it is the same file as mimic.json.

**Comment by Drwr97** [comment]
I have already tried substitutions, but the json file you provided does not contain the keys "images" and "filename" (lines 13 and 17 of extract_clip_feature.py).

**Comment by Drwr97** [comment]
I have already tried substitutions, but the json file you provided does not contain the keys "images" and "filename" (lines 13 and 17 of extract_clip_feature.py).

**Comment by wang-zhanyu** [comment]
Sorry for the misunderstanding. Please download the file from this link: https://drive.google.com/file/d/1tprXEHk1eXI0-Uh6c0Y4LzyCYaeLQ6zd/view?usp=sharing

**Comment by Drwr97** [comment]
Thank you very much for your help. It is very helpful to me.
